output   = "src/model"
pkgname = "model"
wipe     = true
no-tests = true
add-enum-types = true

[psql]
dbname = "sagra_go"
host = "localhost"
user = "sagra"
pass = "sagra"
port   = 5432
schema = "public"
blacklist = ["migrations"]
sslmode = "disable"

