development:
  dialect: postgres
  datasource: host=${DB_SERVER} dbname=${DB_NAME} user=${DB_USER} password=${DB_PASSWORD} sslmode=disable
  dir: migrations/postgres
  table: migrations
test:
  dialect: postgres
  datasource: host=${DB_SERVER} dbname=sagra_test user=${DB_USER} password=${DB_PASSWORD} sslmode=disable
  dir: migrations/postgres
  table: migrations
