development:
  dialect: postgres
  datasource: host=localhost dbname=sagra user=${DB_USER} password=${DB_PASSWORD} sslmode=disable
  dir: migrations/postgres
  table: migrations
test:
  dialect: postgres
  datasource: host=localhost dbname=sagra_test user=${DB_USER} password=${DB_PASSWORD} sslmode=disable
  dir: migrations/postgres
  table: migrations
