version: '3.1'

services:
  db:
    container_name: sagra_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: sagra
      POSTGRES_PASSWORD: sagra
      POSTGRES_DB: sagra_dev
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
