version: '3.1'

services:
  db:
    container_name: sagra_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: sagra
      POSTGRES_PASSWORD: sagra
      POSTGRES_DB: sagra_go
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  go:
    container_name: server
    build: ./go/
    restart: always
    environment:
      DB_URL: "postgresql://sagra:sagra@sagra_db/sagra?sslmode=disable"
      STORE_KEY: secret-key
      PORT: 8080
      ADDRESS: 127.0.0.1
    depends_on:
      - db
    ports:
      - 8080:8080
